registry:
    restart: always
    image: registry:2
    ports:
        - 5000:5000
        - 5001:5001
    volumes:
        - ../../certs:/certs
        - ../../data:/var/lib/registry
        - ./config.yml:/etc/docker/registry/config.yml
    links:
        - token

token:
    image: cesanta/docker_auth:stable
    volumes:
        - ./:/config:ro
        - ../../log/docker_auth:/logs
